# Generated by Django 4.1.7 on 2023-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_food_delete_answer_delete_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="food_name",
            field=models.CharField(db_column="food_name", default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name="food",
            name="serving_size",
            field=models.IntegerField(db_column="serving_size", default=0),
        ),
    ]
