# Generated by Django 4.1.7 on 2023-05-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
