# Generated by Django 4.1.7 on 2023-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='usage_flag',
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(db_column='age', default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.IntegerField(db_column='height', default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.IntegerField(db_column='weight', default=0),
        ),
    ]
